<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class AtlasWallet extends Model
{
    use HasUuids;

    protected $fillable = [
        'user_id',
        'network',
        'token',
        'address',
        'balance',
        'total_deposited',
        'total_withdrawn',
        'total_converted',
        'is_active',
        'last_activity_at',
    ];

    protected function casts(): array
    {
        return [
            'balance'          => 'decimal:8',
            'total_deposited'  => 'decimal:8',
            'total_withdrawn'  => 'decimal:8',
            'total_converted'  => 'decimal:8',
            'is_active'        => 'boolean',
            'last_activity_at' => 'datetime',
        ];
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function formattedBalance(): string
    {
        return number_format((float) $this->balance, 4) . ' ' . $this->token;
    }

    // Generate a simulated wallet address for demo
    // Production: generated by actual blockchain node or custodian
    public static function generateAddress(string $network): string
    {
        $prefixes = [
            'bep20'    => '0x',
            'erc20'    => '0x',
            'polygon'  => '0x',
            'arbitrum' => '0x',
            'trc20'    => 'T',
            'solana'   => '',
        ];
        $prefix = $prefixes[$network] ?? '0x';
        $hex    = bin2hex(random_bytes(20));
        return $prefix . strtoupper($hex);
    }
}
